version: "3.9"
services:
  user:
    image: user-api.main
    container_name: user-api
    restart: unless-stopped
    ports:
      - "4141:8080"
    depends_on:
      - maria_db
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "LOGGING_LEVEL_PMB_USER=INFO"
      - "SPRING_DATASOURCE_URL=jdbc:mariadb://maria_db:3307/user"
  maria_db:
    image: "tobi312/rpi-mariadb:10.11-alpine"
    restart: unless-stopped
    container_name: user-db
    volumes:
      - ./user-api-mariadb-data:/var/lib/mysql:rw
    ports:
      - "3307:3306"
    environment:
      MARIADB_DATABASE: user
      MARIADB_USER: root
      MARIADB_PASSWORD: user
      MARIADB_ROOT_PASSWORD: user
