spring:
  application:
    name: user-api
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: user
  liquibase:
    database-change-log-lock-table: USER_DATABASECHANGELOGLOCK
    database-change-log-table: USER_DATABASECHANGELOG
    change-log: classpath:db/master.xml
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.generate_statistics: false
  jackson.time-zone: Europe/Paris
management:
  endpoints.web.exposure.include: "*"
  endpoints.jmx.exposure.exclude: "*"

springdoc:
  version: 1.5.10
  api-docs.path: /api-docs
  model-converters.pageable-converter.enabled: true

jwt.secretkey: secretkey
